name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository and ensure all branches are fetched
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout the master branch and run lint, test, and build
      - name: Checkout master
        run: git checkout master

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Run lint on master
        run: npx nx affected -t lint --base=HEAD~1 --head=HEAD

      - name: Run tests on master
        run: npx nx affected -t test --base=HEAD~1 --head=HEAD

      - name: Build on master
        run: npx nx affected -t build --base=HEAD~1 --head=HEAD

      # Checkout the PR branch and run lint, test, and build
      - name: Checkout PR branch
        run: git checkout ${{ github.head_ref }}

      - name: Run lint on PR branch
        run: npx nx affected -t lint --base=master --head=${{ github.head_ref }}

      - name: Run tests on PR branch
        run: npx nx affected -t test --base=master --head=${{ github.head_ref }}

      - name: Build on PR branch
        run: npx nx affected -t build --base=master --head=${{ github.head_ref }}
